### ISSUE TITLE
[doc][question] Author property in notion database Type

### ISSUE THREAD

**Issue by CeranaGit** [egrzeszczak/nuxt3-blog#2]
Is the Author type Person?
Before: 

Title | Description | Category | Author | Date | Visible
-- | -- | -- | -- | -- | --
type: Key | type: Text | type: Multi-select | type: User | type: Date | type: Checkbox

After: 

Title | Description | Category | Author | Date | Visible
-- | -- | -- | -- | -- | --
type: Key | type: Text | type: Multi-select | type:Person | type: Date | type: Checkbox

**Comment by egrzeszczak** [comment]
Hello,

Yes the property name in Notion itself has changed to `person`. Will change that soon
